export { default as Footer } from './Footer'
export { default as NameForm } from './Forms/NameForm'
export { default as AlternativesForm } from './Forms/Alternatives'
export { default as GithubCorner } from './GithubCorner'
export { default as HeadTags } from './HeadTags'
export { default as QuizBackground } from './QuizBackground'
export { default as QuizLogo } from './QuizLogo'
export { default as Widget } from './Widget'
export { QuizContainer } from './QuizContainer'
export { default as Button } from './Button'
export { default as Question } from './Question'
export { default as Loading } from './Loading'
export { default as AnswerResult } from './AnswerResult'
export { default as FinalResult } from './FinalResult'